import {
  UserProfile,
  Category,
  Template,
  Invitation,
  InvitationSection,
  GalleryImage,
  StoryItem,
  Guest,
  RSVP,
  Wish,
  InvitationView,
  Gift,
  Signature,
  Feedback,
  SubscriptionPlan,
  UserSubscription,
  Notification,
  AuditLog,
  PaymentOrder,
} from '@/types/database.types';

export interface MockStore {
  users: UserProfile[];
  categories: Category[];
  templates: Template[];
  invitations: Invitation[];
  sections: InvitationSection[];
  galleryImages: GalleryImage[];
  storyItems: StoryItem[];
  guests: Guest[];
  rsvps: RSVP[];
  wishes: Wish[];
  views: InvitationView[];
  gifts: Gift[];
  signatures: Signature[];
  feedback: Feedback[];
  subscriptionPlans: SubscriptionPlan[];
  userSubscriptions: UserSubscription[];
  notifications: Notification[];
  auditLogs: AuditLog[];
  paymentOrders: PaymentOrder[];
}

export const mockCategories: Category[] = [
  { id: 'cat-wedding', name: 'Đám Cưới', slug: 'dam-cuoi', description: 'Mẫu thiệp cưới sang trọng, thanh lịch', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'cat-birthday', name: 'Sinh Nhật', slug: 'sinh-nhat', description: 'Mẫu thiệp mừng tuổi mới tươi vui, ngọt ngào', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'cat-housewarming', name: 'Tân Gia', slug: 'tan-gia', description: 'Mẫu thiệp mừng tân gia ấm cúng, may mắn', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'cat-graduation', name: 'Tốt Nghiệp', slug: 'tot-nghiep', description: 'Mẫu thiệp lễ tốt nghiệp trang trọng', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'cat-anniversary', name: 'Kỷ Niệm', slug: 'ky-niem', description: 'Mẫu thiệp kỷ niệm ngày cưới & tình yêu', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'cat-party', name: 'Tiệc Họp Mặt', slug: 'tiec-hop-mat', description: 'Mẫu thiệp họp lớp, liên hoan gia đình', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
];

export const mockTemplates: Template[] = [
  {
    id: 'tpl-romantic-rose',
    category_id: 'cat-wedding',
    name: 'Romantic Rose',
    slug: 'romantic-rose',
    thumbnail_url: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=600&q=80',
    preview_url: '/templates/romantic-rose',
    theme_config: {
      primaryColor: '#B76E79',
      secondaryColor: '#8FA79B',
      headingFont: 'Cormorant Garamond',
      bodyFont: 'Montserrat',
      heroStyle: 'fullscreen-parallax',
    },
    default_sections: [
      { section_type: 'HERO', display_order: 1, is_visible: true },
      { section_type: 'INTRO', display_order: 2, is_visible: true },
      { section_type: 'COUNTDOWN', display_order: 3, is_visible: true },
      { section_type: 'EVENT', display_order: 4, is_visible: true },
      { section_type: 'MAP', display_order: 5, is_visible: true },
      { section_type: 'STORY', display_order: 6, is_visible: true },
      { section_type: 'GALLERY', display_order: 7, is_visible: true },
      { section_type: 'GIFT', display_order: 8, is_visible: true },
      { section_type: 'SIGNATURE', display_order: 9, is_visible: true },
      { section_type: 'RSVP', display_order: 10, is_visible: true },
      { section_type: 'GUESTBOOK', display_order: 11, is_visible: true },
      { section_type: 'FOOTER', display_order: 12, is_visible: true },
    ],
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'tpl-elegant-beige',
    category_id: 'cat-wedding',
    name: 'Elegant Beige',
    slug: 'elegant-beige',
    thumbnail_url: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=600&q=80',
    preview_url: '/templates/elegant-beige',
    theme_config: {
      primaryColor: '#8FA79B',
      secondaryColor: '#D4AF37',
      headingFont: 'Playfair Display',
      bodyFont: 'Inter',
    },
    default_sections: [
      { section_type: 'HERO', display_order: 1, is_visible: true },
      { section_type: 'INTRO', display_order: 2, is_visible: true },
      { section_type: 'EVENT', display_order: 3, is_visible: true },
      { section_type: 'MAP', display_order: 4, is_visible: true },
      { section_type: 'RSVP', display_order: 5, is_visible: true },
      { section_type: 'FOOTER', display_order: 6, is_visible: true },
    ],
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'tpl-birthday-pastel',
    category_id: 'cat-birthday',
    name: 'Birthday Pastel',
    slug: 'birthday-pastel',
    thumbnail_url: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=600&q=80',
    preview_url: '/templates/birthday-pastel',
    theme_config: {
      primaryColor: '#e85d75',
      secondaryColor: '#F7C59F',
      headingFont: 'Outfit',
      bodyFont: 'Inter',
    },
    default_sections: [
      { section_type: 'HERO', display_order: 1, is_visible: true },
      { section_type: 'COUNTDOWN', display_order: 2, is_visible: true },
      { section_type: 'EVENT', display_order: 3, is_visible: true },
      { section_type: 'RSVP', display_order: 4, is_visible: true },
      { section_type: 'FOOTER', display_order: 5, is_visible: true },
    ],
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockUsers: UserProfile[] = [
  {
    id: 'usr-demo-01',
    email: 'minh.anh@gmail.com',
    full_name: 'Minh & Anh',
    phone: '0901234567',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    role: 'USER',
    status: 'ACTIVE',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'usr-admin-01',
    email: 'admin@nhacotiec.vn',
    full_name: 'Administrator',
    phone: '0987654321',
    avatar_url: null,
    role: 'ADMIN',
    status: 'ACTIVE',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockSubscriptionPlans: SubscriptionPlan[] = [
  {
    id: 'plan-free',
    tier: 'FREE',
    name: 'Free Plan',
    price_vnd: 0,
    max_invitations: 1,
    max_images_per_invitation: 10,
    max_views_per_invitation: 300,
    allow_custom_qr: false,
    allow_custom_music: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'plan-basic',
    tier: 'BASIC',
    name: 'Basic Plan',
    price_vnd: 169000,
    max_invitations: 5,
    max_images_per_invitation: 50,
    max_views_per_invitation: 5000,
    allow_custom_qr: true,
    allow_custom_music: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'plan-premium',
    tier: 'PREMIUM',
    name: 'Premium Plan',
    price_vnd: 269000,
    max_invitations: 999,
    max_images_per_invitation: 100,
    max_views_per_invitation: 999999,
    allow_custom_qr: true,
    allow_custom_music: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockStore: MockStore = {
  users: [...mockUsers],
  categories: [...mockCategories],
  templates: [...mockTemplates],
  invitations: [
    {
      id: 'inv-demo-01',
      user_id: 'usr-demo-01',
      template_id: 'tpl-romantic-rose',
      category_id: 'cat-wedding',
      title: 'Đám Cưới Minh & Anh',
      slug: 'minh-anh',
      cover_title: 'SAVE OUR DATE',
      host_name: 'Minh Hoàng & Ngọc Anh',
      description: 'Hân hạnh kính mời quý khách đến chung vui cùng gia đình chúng tôi trong ngày trọng đại.',
      event_date: '2026-10-20',
      event_start_time: '11:00',
      event_end_time: '14:00',
      venue_name: 'Trung Tâm Hội Nghị Tiệc Cưới White Palace',
      venue_address: '194 Hoàng Văn Thụ, Phường 9, Quận Phú Nhuận, TP. Hồ Chí Minh',
      latitude: 10.7983,
      longitude: 106.6749,
      map_url: 'https://maps.google.com/?q=White+Palace+Hoang+Van+Thu',
      primary_color: '#B76E79',
      secondary_color: '#8FA79B',
      heading_font: 'Cormorant Garamond',
      body_font: 'Montserrat',
      music_url: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8bbf853e8.mp3',
      status: 'PUBLISHED',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      published_at: new Date().toISOString(),
    },
  ],
  sections: [
    { id: 'sec-01', invitation_id: 'inv-demo-01', section_type: 'HERO', display_order: 1, is_visible: true, content_json: { title: 'Lễ Thành Hôn', subtitle: 'Minh Hoàng & Ngọc Anh' }, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 'sec-02', invitation_id: 'inv-demo-01', section_type: 'INTRO', display_order: 2, is_visible: true, content_json: { groom_name: 'Minh Hoàng', bride_name: 'Ngọc Anh' }, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 'sec-03', invitation_id: 'inv-demo-01', section_type: 'COUNTDOWN', display_order: 3, is_visible: true, content_json: {}, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 'sec-04', invitation_id: 'inv-demo-01', section_type: 'EVENT', display_order: 4, is_visible: true, content_json: {}, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 'sec-05', invitation_id: 'inv-demo-01', section_type: 'MAP', display_order: 5, is_visible: true, content_json: {}, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 'sec-06', invitation_id: 'inv-demo-01', section_type: 'STORY', display_order: 6, is_visible: true, content_json: {}, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 'sec-07', invitation_id: 'inv-demo-01', section_type: 'GALLERY', display_order: 7, is_visible: true, content_json: {}, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 'sec-08', invitation_id: 'inv-demo-01', section_type: 'GIFT', display_order: 8, is_visible: true, content_json: {}, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 'sec-09', invitation_id: 'inv-demo-01', section_type: 'SIGNATURE', display_order: 9, is_visible: true, content_json: {}, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 'sec-10', invitation_id: 'inv-demo-01', section_type: 'RSVP', display_order: 10, is_visible: true, content_json: {}, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 'sec-11', invitation_id: 'inv-demo-01', section_type: 'GUESTBOOK', display_order: 11, is_visible: true, content_json: {}, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 'sec-12', invitation_id: 'inv-demo-01', section_type: 'FOOTER', display_order: 12, is_visible: true, content_json: {}, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  ],
  galleryImages: [
    { id: 'img-01', invitation_id: 'inv-demo-01', image_url: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80', caption: 'Khoảnh khắc ngọt ngào', display_order: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 'img-02', invitation_id: 'inv-demo-01', image_url: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=800&q=80', caption: 'Ngày hẹn ước', display_order: 2, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 'img-03', invitation_id: 'inv-demo-01', image_url: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&w=800&q=80', caption: 'Hạnh phúc ngập tràn', display_order: 3, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  ],
  storyItems: [
    { id: 'sty-01', invitation_id: 'inv-demo-01', title: 'Lần đầu gặp gỡ', date: '2022-04-12', description: 'Ngày chúng mình lần đầu gặp gỡ tại quán cà phê góc phố.', image_url: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=600&q=80', display_order: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 'sty-02', invitation_id: 'inv-demo-01', title: 'Lời cầu hôn', date: '2025-12-24', description: 'Dưới ánh hoàng hôn Đà Lạt, em đã nói lời đồng ý.', image_url: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=600&q=80', display_order: 2, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  ],
  guests: [
    { id: 'gst-01', invitation_id: 'inv-demo-01', name: 'Nguyễn Văn A', slug: 'nguyen-van-a', phone: '0912345678', email: 'vana@example.com', group_name: 'Bạn thân', max_guests: 2, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 'gst-02', invitation_id: 'inv-demo-01', name: 'Trần Thị B', slug: 'tran-thi-b', phone: '0987654321', email: 'thib@example.com', group_name: 'Đồng nghiệp', max_guests: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 'gst-03', invitation_id: 'inv-demo-01', name: 'Lê Hoàng C', slug: 'le-hoang-c', phone: '0905123456', email: 'hoangc@example.com', group_name: 'Gia đình', max_guests: 4, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  ],
  rsvps: [
    { id: 'rsvp-01', guest_id: 'gst-01', attendance: 'ATTENDING', guest_count: 2, note: 'Rất vui được đến dự!', submitted_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 'rsvp-02', guest_id: 'gst-02', attendance: 'NOT_ATTENDING', guest_count: 0, note: 'Chúc hai bạn trăm năm hạnh phúc!', submitted_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  ],
  wishes: [
    { id: 'wsh-01', invitation_id: 'inv-demo-01', guest_id: 'gst-01', guest_name: 'Nguyễn Văn A', message: 'Chúc hai bạn mãi mãi hạnh phúc, sớm đón quý tử nhé!', is_visible: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 'wsh-02', invitation_id: 'inv-demo-01', guest_id: null, guest_name: 'Người Bạn Ẩn Danh', message: 'Chúc mừng hạnh phúc lứa đôi! Một đám cưới tuyệt đẹp.', is_visible: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  ],
  views: [
    { id: 'vw-01', invitation_id: 'inv-demo-01', guest_id: 'gst-01', session_id: 'sess-01', viewed_at: new Date().toISOString() },
    { id: 'vw-02', invitation_id: 'inv-demo-01', guest_id: null, session_id: 'sess-02', viewed_at: new Date().toISOString() },
    { id: 'vw-03', invitation_id: 'inv-demo-01', guest_id: 'gst-03', session_id: 'sess-03', viewed_at: new Date().toISOString() },
  ],
  gifts: [
    {
      id: 'gift-01',
      invitation_id: 'inv-demo-01',
      title: 'Quà Mừng Chúc Phúc',
      description: 'Sự hiện diện của quý khách là niềm vinh hạnh lớn nhất của chúng tôi. Nếu gửi quà mừng từ xa, quý khách có thể chuyển khoản qua tài khoản dưới đây.',
      bank_name: 'Vietcombank (VCB)',
      account_name: 'NGUYEN MINH HOANG',
      account_number: '012345678910',
      qr_image_url: 'https://api.vietqr.io/image/970436-012345678910-compact.jpg?amount=0&accountName=NGUYEN%20MINH%20HOANG',
      is_visible: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  signatures: [
    {
      id: 'sig-01',
      invitation_id: 'inv-demo-01',
      guest_id: 'gst-01',
      guest_name: 'Nguyễn Văn A',
      message: 'Mãi mãi hạnh phúc nhé hai người bạn tuyệt vời của tôi!',
      signature_image_url: null,
      is_visible: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  feedback: [
    {
      id: 'fb-01',
      user_id: 'usr-demo-01',
      type: 'FEATURE',
      title: 'Đề xuất thêm hiệu ứng pháo hoa',
      content: 'Giao diện thiệp rất đẹp! Mong nền tảng có thêm hiệu ứng pháo hoa bay khi mở thiệp.',
      rating: 5,
      status: 'RESOLVED',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  subscriptionPlans: [...mockSubscriptionPlans],
  userSubscriptions: [
    {
      id: 'sub-01',
      user_id: 'usr-demo-01',
      plan_id: 'plan-basic',
      started_at: new Date().toISOString(),
      expires_at: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  notifications: [
    {
      id: 'notif-01',
      user_id: 'usr-demo-01',
      type: 'RSVP_RECEIVED',
      title: 'Phản hồi RSVP mới',
      message: 'Khách mời Nguyễn Văn A vừa xác nhận tham dự (2 người).',
      read_at: null,
      created_at: new Date(Date.now() - 3600000).toISOString(),
    },
    {
      id: 'notif-02',
      user_id: 'usr-demo-01',
      type: 'WISH_RECEIVED',
      title: 'Lời chúc mới',
      message: 'Trần Thị B đã gửi lời chúc mừng tới ngày vui của bạn.',
      read_at: null,
      created_at: new Date(Date.now() - 7200000).toISOString(),
    },
    {
      id: 'notif-03',
      user_id: 'usr-demo-01',
      type: 'INVITATION_PUBLISHED',
      title: 'Thiệp cưới đã xuất bản',
      message: 'Thiệp cưới "Đám Cưới Minh & Anh" đã được xuất bản công khai thành công.',
      read_at: new Date(Date.now() - 86400000).toISOString(),
      created_at: new Date(Date.now() - 86400000).toISOString(),
    },
  ],
  auditLogs: [
    {
      id: 'audit-01',
      user_id: 'usr-admin-01',
      action: 'ADMIN_LOGIN',
      resource_type: 'AUTH',
      resource_id: 'usr-admin-01',
      created_at: new Date(Date.now() - 86400000).toISOString(),
    },
    {
      id: 'audit-02',
      user_id: 'usr-admin-01',
      action: 'UPDATE_TEMPLATE',
      resource_type: 'TEMPLATE',
      resource_id: 'tpl-romantic-rose',
      created_at: new Date(Date.now() - 43200000).toISOString(),
    },
  ],
  paymentOrders: [
    {
      id: 'ord-demo-01',
      user_id: 'usr-demo-01',
      subscription_plan_id: 'plan-basic',
      order_code: 'ZLP3018',
      amount: 299000,
      discount_amount: 130000,
      final_amount: 169000,
      currency: 'VND',
      payment_method: 'QR_TRANSFER',
      status: 'WAITING_CONFIRMATION',
      transfer_content: 'ZLP3018',
      bank_name: 'DEMO BANK',
      account_number: '0000000000',
      account_name: 'DEMO ACCOUNT',
      qr_code_url: 'https://api.qrserver.com/v1/create-qr-code/?size=320x320&data=ZLP3018',
      expires_at: new Date(Date.now() + 600000).toISOString(),
      paid_at: null,
      created_at: new Date(Date.now() - 120000).toISOString(),
      updated_at: new Date(Date.now() - 60000).toISOString(),
    },
  ],
};
